# Generated by Django 4.2 on 2024-05-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_estudiante_fecha_nac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='estudiante_id',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='profesor_id',
            new_name='profesor',
        ),
    ]
